name: Build and Publish C#

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'csharp/MapleStory.OpenAPI/MapleStory.OpenAPI.csproj'

jobs:
  build_and_publish_csharp:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[release]') || startsWith(github.event.head_commit.message, 'release:')
    defaults:
      run:
        working-directory: './csharp'
    env:
      NUGET_TOKEN: ${{ secrets.NUGET_UPLOAD_KEY }}
      PROJECT_NAME: MapleStory.OpenAPI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      - name: Build
        run: |
          echo "Building .NET project"
          dotnet build -c Release "./${{ env.PROJECT_NAME }}"

      - name: Publish to NuGet
        run: |
          echo "Publishing to NuGet"
          dotnet pack -c Release "./${{ env.PROJECT_NAME }}"
          dotnet nuget push ./${{ env.PROJECT_NAME }}/bin/Release/${{ env.PROJECT_NAME }}.*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_TOKEN