name: Build and Publish Java

on:
  workflow_dispatch:

jobs:
  build_and_publish_java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './java'

    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8.0.392+8'

      - name: Build
        run: |
          echo "Building Java project"
          chmod +x ./gradlew
          ./gradlew build

      - name: Publish to Maven Repository
        run: |
          echo "ossrhUsername=${OSSRH_USERNAME}" >> gradle.properties
          echo "ossrhPassword=${OSSRH_PASSWORD}" >> gradle.properties
          echo "gpgSecretKey=${GPG_SECRET_KEY}" >>  gradle.properties
          echo "gpgPassphrase=${GPG_PASSPHRASE}" >> gradle.properties
          echo "Publishing to Maven repository"
          ./gradlew publish
        env:
          GRADLE_USER_HOME: ./gradle