name: Build and Publish Python

on:
  workflow_dispatch:

jobs:
  build_and_publish_js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './python'
    env:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install wheel

      - name: Build package
        run: python3 setup.py sdist bdist_wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}