name: Build and Publish Python

on:
  workflow_dispatch:

jobs:
  build_and_publish_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './python'

    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          pip3 install wheel twine

      - name: Build package
        run: |
          echo "Build Python project"
          python3 setup.py sdist bdist_wheel

      - name: Publish package distributions to PyPI
        run: twine upload --repository-url https://upload.pypi.org/legacy/ -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
